---

- hosts: all 
  gather_facts: true
  become: true

  # The variables you would most likely want/need to override have been included
  vars:
    # Directories
    #client_sw_dir: "/root/SAS-5.0.7/client"
    #client_sw_tmp_dir: /tmp/1id

    # Facts
    #client_preflight_facts_generate: true
    #client_preflight_facts_verbose: false

    # Reports
    #client_preflight_reports_generate: true
    #client_preflight_reports_backup: false

    # Active Directory
    #client_domain: sample.net
    #client_username: user
    #client_password: pass

  roles:
    - name: oneidentity.authentication_services.client_preflight
