- name: copy packages
  hosts: all
  become: true

  tasks:
  - name: mkdir /root/sas
    ansible.builtin.file:
      path: /root/sas
      state: directory
     
  - name: Copy vasgp packages
    ansible.builtin.copy:
      src: ./client/linux-x86_64/vasgp_5.0.3-39941_amd64.deb
      dest: /root/sas
      
  - name: Copy vasclnt packages
    ansible.builtin.copy:
      src: ./client/linux-x86_64/vasclnt_5.0.3-39941_amd64.deb
      dest: /root/sas
      
  - name: Copy preflight
    ansible.builtin.copy:
      src: ./client/linux-x86_64/preflight
      dest: /root/sas
      mode: "0755"
