- name: copy packages
  hosts: all
  become: true

  tasks: 
  - name: run some command  
    command: "ls -Al /"
    delegate_to: localhost

  - name: run some command  
    command: "ls -Al /var"
    delegate_to: localhost


  - name: run some command  
    command: "ls -Al /var/lib"
    delegate_to: localhost

  - name: run some command  
    command: "ls -Al /var/lib/awx"
    delegate_to: localhost

  - name: run some command  
    command: "pwd"
    delegate_to: localhost


  - name: first task
    ansible.builtin.copy:
      src: /var/lib/awx/projects/client
      dest: /tmp/
