- name: copy packages
  hosts: all
  become: true

  - name: Create Directory
    file:
     path: /root/sas
     state: directory
     
  - name: first task
    ansible.builtin.copy:
      src: ./client/linux-x86_64
      dest: /root/sas
