- name: copy packages
  hosts: all
  become: true

  tasks: 
  - name: run some command  
    command: "mkdir /root/sas"
    delegate_to: localhost

  - name: first task
    ansible.builtin.copy:
      src: ./client/linux-x86_64
      dest: /root/sas
